### PR TITLE
added decode("utf-8") to check_cert_not_after to convert bytes to str…

### PR DESCRIPTION
**Pull request by rabos5**
…ing which fails with newer version of Python openssl

### CODE REVIEW

**Comment by vog** [comment]
Thanks for your contribution!

I have three questions, though:

1. Which versions of Python, OpenSSL and PyOpenSSL are you using? I tried hard to reproduce this issue, but the current release worked well in every combination I tried.
2. Which error message did you get?
3. Shouldn't the patch also work with `.decode('ascii')` instead of `.decode('utf-8')`?

As soon as this is clarified, I'll create a new release that contains the fix.

**Comment by rabos5** [comment]
Hey sorry,

I knew right after submitting that I should have included that information.  Here are your answers, hope this helps.

1.  I am using:
     * Python 3.6.5
     * openssl LibreSSL 2.2.7
     * pyOpenSSL version 18.0.0
2.  Here is the error stacktrace:
```
File "/usr/local/lib/python3.6/site-packages/requests_pkcs12.py", line 108, in post
    return request('post', *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests_pkcs12.py", line 84, in request
    pkcs12_password=pkcs12_password,
  File "/usr/local/lib/python3.6/site-packages/requests_pkcs12.py", line 53, in __init__
    super(Pkcs12Adapter, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 126, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/usr/local/lib/python3.6/site-packages/requests_pkcs12.py", line 56, in init_poolmanager
    kwargs['ssl_context'] = self._create_ssl_context()
  File "/usr/local/lib/python3.6/site-packages/requests_pkcs12.py", line 66, in _create_ssl_context
    check_cert_not_after(cert)
  File "/usr/local/lib/python3.6/site-packages/requests_pkcs12.py", line 28, in check_cert_not_after
    cert_not_after = datetime.strptime(cert.get_notAfter(), '%Y%m%d%H%M%SZ')
TypeError: strptime() argument 1 must be str, not bytes
```

3.  Yep this works with `.decode('ascii')` as well as `.decode('utf-8')`

Let me know if you have any other questions for me.

Ryan

**Comment by vog** [comment]
Ah, I see. So this is not a problem with recent OpenSSL libraries, but with recent Python versions (namely, recent `datetime` implementations). That makes a lot more sense now.

**Comment by vog** [comment]
Would you mind to change `decode('utf-8')` to `decode('ascii')` in your pull request?

**Comment by rabos5** [comment]
Yep just pushed a new commit to change it to ascii.

**Comment by vog** [comment]
Thanks!

**Comment by vog** [comment]
New release:

* https://pypi.org/project/requests-pkcs12/1.2/

**Pull request merged**
