### PR TITLE
Keep ssl context

### PR DESCRIPTION
**Pull request by rashley-iqt**

### CODE REVIEW

**Comment by vog** [comment]
Looks good so far. However, the `_create_ssl_context` helper is no longer a method, but a plain function. Please mark it either as `@static` method, or move it as a vanilla function outside the `Pkcs12Adapter` class.

**Comment by rashley-iqt** [comment]
I moved `_create_ssl_context` to a vanilla function out side of the class.  My thinking was to make it something that could be imported without necessarily bringing in the whole class if so desired.

**Comment by rashley-iqt** [comment]
Have you had a chance to review the updated changeset?

**Comment by vog** [comment]
Thanks for providing an improved pull request. I'll try to test it as soon as possible, perhaps today or tomorrow.

**Comment by sodre** [comment]
@vog, any updates on merging this change?

**Comment by vog** [comment]
I'm very sorry for the delay. I'll have a look at it as soon as possible.

**Comment by vog** [comment]
@rashley-iqt: Thanks again for your contribution.

Unfortunately, you combined this pull request with an additional commit, which is using a different `PROTOCOL_*` constant. This is a different topic and needs further discussion. It would have been better to provide that as a separate pull request, so we can discuss this separately and not having that change blocking this pull request.

**Comment by vog** [comment]
My tests were all successful.

I committed your pull request partially, including only those parts relevant for this topic, i.e. no gitignore or PROTOCOL things.

Then, I added some improvements over the PROTOCOL things. In case that doesn't fit your needs, feel free to open a separate issue and/or pull request for that.

I released a new version 1.3 to PIP.

Again, thanks!

**Comment by sodre** [comment]
Thank @vog!  I just updated the conda-forge/requests_pkcs12-feedstock to 1.3 as well.

**Pull request closed without merging**
